name: CI

on:
  pull_request:
    paths:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - run: dotnet new install ./templates
      - run: dotnet new eternet-api -n Sample -o Sample
      - run: dotnet build Sample/Sample.csproj -c Release --no-restore --verbosity minimal
      - run: |
          cd Eternet.Api.Accounting
          dotnet build tests/Eternet.Accounting.Api.Tests.sln -c Release --no-restore --verbosity minimal
          dotnet test tests/Eternet.Accounting.Api.Tests.sln -c Release --no-build --no-restore --verbosity minimal
      - run: |
          cd ../Eternet.Web
          dotnet build src/Eternet.Web.sln -c Release --no-restore
          dotnet test tests/Eternet.Web.Infrastructure.Tests/Eternet.Web.Infrastructure.Tests.csproj --no-build --no-restore --verbosity minimal
          dotnet test src/tests/Eternet.Web.UI.Tests/Eternet.Web.UI.Tests.csproj -c Release --no-build --no-restore --verbosity minimal
